---
title: "ALLEVI"
author: "Esther Allevi"
format: html
---

## Introduction

### Study organisation

```{r}
#|message : false
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
```


#### Question 1

```{r}
here::i_am("lab-grades.Rproj")
```

```{r}
courses <- vroom("courses.csv")
```

#### Question 2 

```{r}
courses |>
  rename(`course name` = course, "identifier" = course_id, `number of exams`= "nb_grades") |>
  knitr::kable()
```

### Students

#### Question 3

```{r}
students <- vroom("students.csv")
```

```{r}
# Checking the types
cols_type = cols(
  id = col_double(),
  group = col_double(),
  birth_date = col_date(format = ""),
  sex = col_character(),
  .delim = ","
)
```

```{r}
students <- students |>
  mutate(
    id = as.integer(id),
    group = as.factor(group),
    sex = as.factor(sex)
  )
```

```{r}
typeof(students$group) # checking
```

The `{r} "birth_date"` column of the `{r} "students"` data frame is of class `{r} class(students$birth_date)`.

**PROBLÈME RENDERING**

### Grades

```{r}
# Check, not sure if properly cleaned
grades_clean <- read_delim(here("grades.csv"),
  delim = ";",
  na = "$")
```

## Student population analysis

#### Question 5

```{r}
students |>
  summarise(`Number of students per group` = n(), .by = group) |>
  ggplot(aes(x = group, y = `Number of students per group`)) + 
    geom_col() 
```

#### Question 6

```{r}
students |>
    summarise(`Number of students per group` = n(), .by = c(group, sex)) |>
  ggplot(aes(x = group, y = `Number of students per group`, fill = sex)) + 
    geom_col() 
```




